// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infrastructure.Data;

#nullable disable

namespace infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241224215050_firstmig")]
    partial class firstmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataPoint10Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint1Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint2Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint3Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint4Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint5Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint6Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint7Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint8Value")
                        .HasColumnType("int");

                    b.Property<int>("DataPoint9Value")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DataRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
